meta_product_name: "Joyage"
meta_title: "Joyage - Plan your next trip with friends"
meta_description: "Find afforable trips for you and your friends from all over the world."
meta_image: "Joyage_big.png" # should exist in `app/assets/images/`
